# trigger:
#   - main

pool:
  name: Default

variables:
  azureSubscription: 'cost-connection'
  functionAppName: 'apptestdeploy'

steps:
  - task: ArchiveFiles@2
    displayName: 'Archive Function App'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: zip
      archiveFile: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
      replaceExistingArchive: true

  - task: AzureFunctionApp@2
    displayName: 'Deploy to Azure Function App'
    inputs:
      azureSubscription: '$(azureSubscription)'
      appType: functionAppLinux
      appName: '$(functionAppName)'
      package: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
      deploymentMethod: 'zipDeploy'