trigger:
  - main

pool:
  name: Default

variables:
  azureSubscription: 'cost-connection'
  functionAppName: 'cost-demo'

steps:
  # Install dependencies locally
  - script: |
      python3.11 -m pip install --upgrade pip
      pip install --target="./.python_packages/lib/site-packages" -r requirements.txt
    displayName: 'Install dependencies'

  - task: ArchiveFiles@2
    displayName: 'Archive Function App'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: zip
      archiveFile: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
      replaceExistingArchive: true

  - task: AzureFunctionApp@2
    displayName: 'Deploy to Azure Function App'
    inputs:
      azureSubscription: '$(azureSubscription)'
      appType: functionAppLinux
      appName: '$(functionAppName)'
      package: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
      deploymentMethod: 'zipDeploy'